import { existsSync, readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { ensureDir } from "./fsutil.js";

const GEN_MD = "<!-- Generated by AgentRig from AGENTS.md + .agents/rules/. Do not edit here — edit the source and run `agentrig compile`. -->";
const GEN_HASH = "# Generated by AgentRig. Do not edit here — edit the source and run `agentrig compile`.";

export interface CompileResult {
  generated: string[];
  skipped: { path: string; reason: string }[];
}

interface Rule {
  name: string;
  globs: string[];
  description: string;
  body: string;
}

/** Extract a section from AGENTS.md: prefer the AGENTRIG marker block, fall back to a `## Heading`. */
function extractAgentsSection(text: string, marker: string, heading: string): string {
  const start = `<!-- AGENTRIG:${marker}:start -->`;
  const end = `<!-- AGENTRIG:${marker}:end -->`;
  const si = text.indexOf(start);
  const ei = text.indexOf(end);
  if (si >= 0 && ei > si) return text.slice(si + start.length, ei).trim();
  // Heading fallback: from "## <heading>" to the next "## ".
  const h = new RegExp(`^##\\s+${heading}.*$`, "mi");
  const m = h.exec(text);
  if (!m) return "";
  const after = text.slice(m.index + m[0].length);
  const nextH = after.search(/^##\s+/m);
  return (nextH < 0 ? after : after.slice(0, nextH)).trim();
}

/** Drop lines still containing unfilled {{PLACEHOLDER}} template tokens. */
function dropPlaceholders(text: string): string {
  return text
    .split("\n")
    .filter((l) => !/\{\{[A-Z0-9_]+\}\}/.test(l))
    .join("\n")
    .trim();
}

function parseGlobs(raw: string | undefined): string[] {
  if (!raw) return ["**/*"];
  const arr = raw.match(/\[(.*)\]/);
  const inner = arr ? arr[1]! : raw;
  const globs = inner
    .split(",")
    .map((s) => s.trim().replace(/^["']|["']$/g, ""))
    .filter(Boolean);
  return globs.length ? globs : ["**/*"];
}

function loadRules(repoRoot: string): Rule[] {
  const dir = join(repoRoot, ".agents", "rules");
  if (!existsSync(dir)) return [];
  const rules: Rule[] = [];
  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".md") || file === "README.md") continue;
    const text = readFileSync(join(dir, file), "utf8");
    const fm = text.startsWith("---") ? text.slice(3, text.indexOf("\n---", 3)) : "";
    const body = text.startsWith("---") ? text.slice(text.indexOf("\n---", 3) + 4).trim() : text.trim();
    const globs = parseGlobs((fm.match(/^\s*globs\s*:\s*(.+)$/m) || [])[1]);
    const description = ((fm.match(/^\s*description\s*:\s*(.+)$/m) || [])[1] || file.replace(/\.md$/, "")).trim();
    rules.push({ name: file.replace(/\.md$/, ""), globs, description, body });
  }
  return rules;
}

function detectSetup(repoRoot: string): { name: string; steps: string } {
  const has = (f: string) => existsSync(join(repoRoot, f));
  if (has("package.json")) {
    let install = "npm install";
    let cache = "npm";
    if (has("pnpm-lock.yaml")) { install = "corepack enable && pnpm install --frozen-lockfile"; cache = "pnpm"; }
    else if (has("yarn.lock")) { install = "corepack enable && yarn install --frozen-lockfile"; cache = "yarn"; }
    else if (has("package-lock.json")) { install = "npm ci"; cache = "npm"; }
    return {
      name: "Node.js",
      steps: `      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "${cache}"
      - name: Install dependencies
        run: ${install}`,
    };
  }
  if (has("pyproject.toml") || has("requirements.txt")) {
    return {
      name: "Python",
      steps: `      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -e . || pip install -r requirements.txt`,
    };
  }
  if (has("go.mod")) {
    return {
      name: "Go",
      steps: `      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Download modules
        run: go mod download`,
    };
  }
  return {
    name: "generic",
    steps: `      # TODO: set up your toolchain and install dependencies here so Copilot's
      # ephemeral environment is ready before it starts working.`,
  };
}

function write(repoRoot: string, rel: string, content: string, result: CompileResult): void {
  const abs = join(repoRoot, rel);
  ensureDir(join(abs, ".."));
  writeFileSync(abs, content.endsWith("\n") ? content : content + "\n");
  result.generated.push(rel);
}

/**
 * Project the canonical source (AGENTS.md + .agents/rules/) into every agent ecosystem's NATIVE
 * surface — local and remote — so any agent benefits without lock-in. Idempotent. Pure projections
 * are regenerated each run; `copilot-setup-steps.yml` is scaffolded once (user-owned).
 */
export function compileSurfaces(repoRoot: string): CompileResult {
  const result: CompileResult = { generated: [], skipped: [] };
  const agentsPath = join(repoRoot, "AGENTS.md");
  if (!existsSync(agentsPath)) {
    result.skipped.push({ path: "AGENTS.md", reason: "missing — run `agentrig init` first" });
    return result;
  }
  const agents = readFileSync(agentsPath, "utf8");
  const critical = extractAgentsSection(agents, "critical-rules", "Critical Rules");
  const context = dropPlaceholders(extractAgentsSection(agents, "context", "What this repository is"));
  const rules = loadRules(repoRoot);

  // --- GitHub Copilot (remote coding agent + IDE): repo-wide custom instructions ---
  write(repoRoot, ".github/copilot-instructions.md", [
    GEN_MD,
    "",
    "# Copilot instructions",
    "",
    critical || "See AGENTS.md for the project's agent instructions.",
    "",
    context ? "## About this repository\n\n" + context + "\n" : "",
    "The full agent guide is in [AGENTS.md](../AGENTS.md). Path-specific rules live in",
    "`.github/instructions/`.",
  ].join("\n"), result);

  // --- GitHub path-scoped instructions, one per rule (applyTo = the rule's globs) ---
  for (const rule of rules) {
    write(repoRoot, `.github/instructions/${rule.name}.instructions.md`, [
      "---",
      `applyTo: "${rule.globs.join(",")}"`,
      "---",
      GEN_MD,
      "",
      rule.body,
    ].join("\n"), result);
  }

  // --- Cursor: .cursor/rules/*.mdc, one per rule ---
  for (const rule of rules) {
    const alwaysApply = rule.globs.length === 1 && rule.globs[0] === "**/*";
    write(repoRoot, `.cursor/rules/${rule.name}.mdc`, [
      "---",
      `description: ${rule.description}`,
      `globs: ${rule.globs.join(",")}`,
      `alwaysApply: ${alwaysApply}`,
      "---",
      GEN_MD,
      "",
      rule.body,
    ].join("\n"), result);
  }

  // --- Claude Code: CLAUDE.md imports AGENTS.md + inlines the critical rules ---
  write(repoRoot, "CLAUDE.md", [
    GEN_MD,
    "",
    "# Claude Code instructions",
    "",
    "@AGENTS.md",
    "",
    critical ? "## Critical rules\n\n" + critical : "",
  ].join("\n"), result);

  // --- MCP: project .mcp.json to the surfaces that read their own location ---
  const mcpPath = join(repoRoot, ".mcp.json");
  if (existsSync(mcpPath)) {
    try {
      const mcp = JSON.parse(readFileSync(mcpPath, "utf8"));
      const servers = mcp.mcpServers ?? mcp.servers ?? {};
      // VS Code reads `.vscode/mcp.json` with a top-level `servers` key.
      write(repoRoot, ".vscode/mcp.json", JSON.stringify({ servers }, null, 2), result);
      // Reference for the GitHub Copilot coding agent (also configurable in repo settings).
      write(repoRoot, ".github/copilot/mcp.json", JSON.stringify({
        $comment: "AgentRig: MCP servers for the Copilot coding agent. Add these in Settings → Copilot → coding agent if not auto-loaded.",
        mcpServers: servers,
      }, null, 2), result);
    } catch {
      result.skipped.push({ path: ".vscode/mcp.json", reason: "could not parse .mcp.json" });
    }
  }

  // --- Remote env: copilot-setup-steps.yml (scaffold once; user-owned thereafter) ---
  const setupRel = ".github/workflows/copilot-setup-steps.yml";
  if (existsSync(join(repoRoot, setupRel))) {
    result.skipped.push({ path: setupRel, reason: "exists (user-owned; left untouched)" });
  } else {
    const setup = detectSetup(repoRoot);
    write(repoRoot, setupRel, `name: "Copilot Setup Steps"
${GEN_HASH}
# Prepares the Copilot coding agent's ephemeral environment (detected stack: ${setup.name}).
# Customize freely — this file is yours after the first scaffold.

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be named \`copilot-setup-steps\` or Copilot will not pick it up.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
${setup.steps}
`, result);
  }

  return result;
}

/** Files compileSurfaces is responsible for (used by audit/checks awareness). */
export function compiledSurfacePaths(repoRoot: string): string[] {
  const paths = [
    ".github/copilot-instructions.md",
    "CLAUDE.md",
    ".vscode/mcp.json",
    ".github/workflows/copilot-setup-steps.yml",
  ];
  const instr = join(repoRoot, ".github", "instructions");
  if (existsSync(instr) && statSync(instr).isDirectory()) paths.push(".github/instructions");
  return paths;
}
